# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'data_juicer'
copyright = '2024, Data-Juicer Team'
author = 'Data-Juicer Team'

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
import sphinx_rtd_theme

from data_juicer import __version__ as version
import os
import sys
from googletrans import Translator
translator = Translator()

sys.path.insert(0, os.path.abspath('../../'))
release = version

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    'sphinx.ext.autodoc',
    "sphinx.ext.autosummary",
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    "sphinx.ext.autosectionlabel",
    "myst_parser",
]

myst_heading_anchors = 2

# Prefix document path to section labels, otherwise autogenerated labels would
# look like 'heading' rather than 'path/to/file:heading'
autosectionlabel_prefix_document = True
autosummary_generate = True
autosummary_ignore_module_all = False

autodoc_member_order = "bysource"

templates_path = ['_templates']
exclude_patterns = ['build']

# -- Options for HTML output -------------------------------------------------

html_theme = 'sphinx_rtd_theme'
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

html_theme_options = {
    "navigation_depth": 4,
    "collapse_navigation": True
}

# language settings
language = 'en'
locale_dirs = ['locale/']   # path is example but recommended.
gettext_compact = False     # optional.

# list of supported languages
supported_languages = {
    'en': 'English',
    'zh_CN': '简体中文',
    'ja': '日本語',
}
html_context = {
    'supported_languages': supported_languages,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# def get_translation(text, target_lang):
#     try:
#         return translator.translate(text, dest=target_lang).text
#     except:
#         return text
    
# get the page path
def get_page_path(app, pagename, templatename, context, doctree):
    current_lang = app.config.language
    
    if current_lang == 'zh_CN':
        # Check if there is a corresponding Chinese translation file
        zh_page = f"{pagename}_ZH"
        if os.path.exists(f"{app.srcdir}/{zh_page}.md"):
            context['page_path'] = zh_page
        else:
            context['page_path'] = pagename
    else:
        context['page_path'] = pagename

    
# automatic translation function
# def auto_translate(app, docname, source):
#     current_lang = app.config.language
    
#     if current_lang == 'ja':
#         # Automatic translation of Japanese
#         source[0] = get_translation(source[0], 'ja')
#         return source[0]

def skip(app, what, name, obj, would_skip, options):
    if name == "__init__":
        return False
    return would_skip

def process_operators(app, docname, source):
    operators_url = "https://github.com/modelscope/data-juicer/blob/main/docs/Operators.md"
    
    import re
    
    def replace_operators_link(match):
        link_text = match.group(1)
        return f'[{link_text}]({operators_url})'

    pattern = r'\[([^\]]+)\]\([^)]*Operators\.md\)'
    source[0] = re.sub(pattern, replace_operators_link, source[0])
    return source[0]

def process_read(app, docname, source):
    source[0] = process_operators(app, docname, source)
    # auto_translate(app, docname, source)

def setup(app):
    app.connect('source-read', process_read)
    app.connect('html-page-context', get_page_path)
    app.connect("autodoc-skip-member", skip)
